const fs = require('fs');
const path = require('path');

// 1. UPDATE APRESENTACAO_FRAME.HTML
const framePath = path.join(__dirname, 'apresentacao_frame.html');
let frameContent = fs.readFileSync(framePath, 'utf8');

// Update p6Text in db.standard (47:75)
const oldFrameP6 = `p6Text: \`Máscara de camada gráfica 2D direta universal: Utilize a primeira imagem anexada (Faca 3 Furos) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde sem adicionar, remover ou alterar NENHUM elemento. Os três furos circulares e o recorte do topo da primeira imagem funcionam como aberturas de perfuração vazada transparente de faca. REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): Os furos de corte NÃO são círculos brancos pintados, mas sim a perfuração e remoção total da arte gráfica de fundo nessa área (transparência vazada de canal alfa sem preenchimento). GEOMETRIA DA FACA PADRÃO (47:75): Os três furos circulares mantêm espaçamento proporcional uniforme de aproximadamente 16 px (2.5 mm a 3.0 mm) entre bordas, estando o furo da direita posicionado no ponto médio perpendicular entre os dois furos verticais da esquerda, replicando exatamente o gabarito CAD físico de linha vermelha. O bloco do logo da marca e subtítulo '[SUBTITULO]' fica posicionado estritamente no terço superior da cartela. Não alterar diâmetro, posição relativa ou espaçamento proporcional dos furos. Não mude de posição nenhum outro elemento gráfico ou artístico. Imagem 2D plana contínua perfeitamente alinhada. --ar 47:75 --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry, no floating circles\``;

const newFrameP6 = `p6Text: \`Máscara de camada gráfica 2D direta universal: Utilize a primeira imagem anexada (Faca 3 Furos) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde sem adicionar, remover ou alterar NENHUM elemento. Os três furos circulares e o recorte do topo da primeira imagem funcionam como aberturas de perfuração vazada transparente de faca. REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): Os furos de corte NÃO são círculos brancos pintados, mas sim a perfuração e remoção total da arte gráfica de fundo nessa área (transparência vazada de canal alfa sem preenchimento). GEOMETRIA E ALINHAMENTO ELEVADO DA FACA PADRÃO (47:75): Os três furos circulares mantêm espaçamento proporcional uniforme de aproximadamente 16 px (2.5 mm a 3.0 mm) entre bordas. ALINHAMENTO VERTICAL DO FURO DA DIREITA: O centro do furo circular da direita deve SUBIR e ficar posicionado na metade da altura exata (ponto médio elevado) entre o furo superior esquerdo e o furo inferior esquerdo, formando um arranjo triangular perfeitamente alinhado sem descair. O bloco do logo da marca e subtítulo '[SUBTITULO]' fica posicionado estritamente no terço superior da cartela. Não alterar diâmetro, posição relativa ou espaçamento proporcional dos furos. Não mude de posição nenhum outro elemento gráfico ou artístico. Imagem 2D plana contínua perfeitamente alinhada. --ar 47:75 --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry, no floating circles\``;

// Update cuts[4] in db.ultimate (1:1)
const oldCut4 = `4: \`Máscara de camada gráfica 2D direta (Frame Ultimate - Faca Corte Modelo 4): Utilize a primeira imagem anexada (Gabarito Faca Corte 4) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde quadrado (1:1) sem alterar nenhum elemento. Os TRÊS FUROS CIRCULARES EM ARRANJO TRIANGULAR DA CÂMERA (PIRÂMIDE) da primeira imagem funcionam como aberturas de perfuração vazada de faca, com o furo da direita totalmente COLADO e tangente aos dois furos da esquerda (vão zero). REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): A arte gráfica é totalmente recortada e apagada dentro da área dos furos (transparência vazada sem círculos brancos pintados). Se o subtítulo '[SUBTITULO]' estiver próximo dos furos superiores, posicione o subtítulo no espaço limpo da parte inferior da cartela. Não mude de posição nenhum outro elemento gráfico. Imagem 2D plana contínua perfeitamente alinhada. --ar 1:1 --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry\``;

const newCut4 = `4: \`Máscara de camada gráfica 2D direta (Frame Ultimate - Faca Corte Modelo 4): Utilize a primeira imagem anexada (Gabarito Faca Corte 4) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde quadrado (1:1) sem alterar nenhum elemento. Os TRÊS FUROS CIRCULARES EM ARRANJO TRIANGULAR DA CÂMERA (PIRÂMIDE) da primeira imagem funcionam como aberturas de perfuração vazada de faca. ALINHAMENTO VERTICAL ELEVADO DO FURO DA DIREITA: O centro do furo da direita deve SUBIR para a metade da altura exata entre o furo superior esquerdo e o furo inferior esquerdo, estando totalmente COLADO e tangente aos dois furos da esquerda (vão zero) sem descair. REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): A arte gráfica é totalmente recortada e apagada dentro da área dos furos (transparência vazada sem círculos brancos pintados). Se o subtítulo '[SUBTITULO]' estiver próximo dos furos superiores, posicione o subtítulo no espaço limpo da parte inferior da cartela. Não mude de posição nenhum outro elemento gráfico. Imagem 2D plana contínua perfeitamente alinhada. --ar 1:1 --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry\``;

if (frameContent.includes(oldFrameP6)) {
    frameContent = frameContent.replace(oldFrameP6, newFrameP6);
    console.log('Successfully updated p6Text in apresentacao_frame.html');
} else {
    console.warn('Could not match oldFrameP6 in apresentacao_frame.html');
}

if (frameContent.includes(oldCut4)) {
    frameContent = frameContent.replace(oldCut4, newCut4);
    console.log('Successfully updated cuts[4] in apresentacao_frame.html');
} else {
    console.warn('Could not match oldCut4 in apresentacao_frame.html');
}

fs.writeFileSync(framePath, frameContent, 'utf8');

// 2. UPDATE APRESENTACAO_INTERATIVA.HTML
const interativaPath = path.join(__dirname, 'apresentacao_interativa.html');
if (fs.existsSync(interativaPath)) {
    let interativaContent = fs.readFileSync(interativaPath, 'utf8');

    const oldInterativaP6 = `p6Text: \`Máscara de camada gráfica 2D direta universal: Utilize a primeira imagem anexada (Faca Mestre) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde sem adicionar, remover ou alterar NENHUM elemento. Os três furos circulares e o recorte do topo da primeira imagem funcionam como aberturas de perfuração vazada transparente de faca. REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): Os furos de corte NÃO são círculos brancos pintados, mas sim a perfuração e remoção total da arte gráfica de fundo nessa área (transparência vazada de canal alfa sem preenchimento). GEOMETRIA DA FACA DA LENTE: Os três furos circulares mantêm espaçamento proporcional uniforme de aproximadamente 16 px (2.5 mm a 3.0 mm) entre bordas, estando o furo da direita posicionado no ponto médio perpendicular entre os dois furos verticais da esquerda, replicando exatamente o gabarito CAD físico original. O bloco do logo da marca e subtítulo '[SUBTITULO]' fica no terço superior. Não alterar diâmetro, posição relativa ou espaçamento proporcional dos furos. Imagem 2D plana contínua perfeitamente alinhada. --ar [PROPORCAO] --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry, no floating circles\``;

    const newInterativaP6 = `p6Text: \`Máscara de camada gráfica 2D direta universal: Utilize a primeira imagem anexada (Faca Mestre) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde sem adicionar, remover ou alterar NENHUM elemento. Os três furos circulares e o recorte do topo da primeira imagem funcionam como aberturas de perfuração vazada transparente de faca. REMOÇÃO ATIVA DE ARTE (EFEITO REMOVE BACKGROUND): Os furos de corte NÃO são círculos brancos pintados, mas sim a perfuração e remoção total da arte gráfica de fundo nessa área (transparência vazada de canal alfa sem preenchimento). GEOMETRIA E ALINHAMENTO ELEVADO DA FACA DA LENTE: Os três furos circulares mantêm espaçamento proporcional uniforme de aproximadamente 16 px (2.5 mm a 3.0 mm) entre bordas. ALINHAMENTO VERTICAL DO FURO DA DIREITA: O centro do furo circular da direita deve SUBIR e ficar posicionado na metade da altura exata (ponto médio elevado) entre o furo superior esquerdo e o furo inferior esquerdo, sem descair. O bloco do logo da marca e subtítulo '[SUBTITULO]' fica no terço superior. Não alterar diâmetro ou posição relativa dos furos. Imagem 2D plana contínua perfeitamente alinhada. --ar [PROPORCAO] --no white circles, no solid white shapes, no painted circles, no drawn holes, no white fills, no box, no 3d mockup, no altered geometry, no floating circles\``;

    if (interativaContent.includes(oldInterativaP6)) {
        interativaContent = interativaContent.replace(oldInterativaP6, newInterativaP6);
        fs.writeFileSync(interativaPath, interativaContent, 'utf8');
        console.log('Successfully updated apresentacao_interativa.html');
    }
}
