const fs = require('fs');

const htmlPath = 'c:/Users/bruno/.gemini/antigravity-ide/scratch/workana_packaging_ai/apresentacao_frame.html';
let html = fs.readFileSync(htmlPath, 'utf8');

const updatedStandardObj = `            standard: {
                badge: 'LINHA FRAME PADRÃO (47 × 75 mm)',
                proporcao: '47:75',
                p1Text: \`Layout gráfico em 2D plano para a face frontal de cartela retangular de protetor de lente de câmera, imagem retangular 2D estritamente plana, proporção 47:75. Reproduza exatamente o estilo visual, cores da marca, fundo, tipografia e logo da imagem de referência anexada. O bloco do logo da marca e subtítulo '[SUBTITULO]' deve ser agrupado de forma compacta e posicionado estritamente na região do terço superior da cartela, mantendo uma margem de segurança limpa do topo, deixando a metade inferior totalmente limpa para a área dos furos das lentes. Imagem retangular plana e contínua sem ícones de benefícios, sem textos pequenos perto da borda, sem molduras perimetrais. --ar 47:75 --no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                pl1Text: \`Adaptação multi-estilo Lote 1 em grade 2x2 para Frame de Lente: Mantenha a proporção 47:75. CADA UM DOS 4 QUADROS DEVE OBRIGATORIAMENTE EXIBIR O LOGO DA MARCA E O SUBTÍTULO '[SUBTITULO]' CENTRALIZADOS NO TERÇO SUPERIOR. TODOS OS PROTETORES DE LENTES DEVEM SER ESTRITAMENTE CIRCULARES E REDONDOS (ANÉIS METÁLICOS CIRCULARES E LENTES DE VIDRO CIRCULARES REDONDAS). Gere uma grade 2x2 com 4 quadros paralelos onde CADA QUADRO APLICA UM ESTILO ARTÍSTICO E UMA POSIÇÃO EXCLUSIVA DE PROTETORES DE LENTES CIRCULARES:
• Quadro 1 (Minimalista Clean): Fundo clean, logo da marca e subtítulo '[SUBTITULO]' no terço superior, vista da parte traseira inteira do smartphone Prata com o módulo de câmeras destacando os 3 anéis protetores de lentes circulares e redondos instalados nas câmeras.
• Quadro 2 (Bauhaus Geométrico): Fundo bauhaus, logo da marca e subtítulo '[SUBTITULO]' no terço superior, somente os 3 anéis protetores de lentes de câmera circulares metálicos redondos flutuando isolados com brilho de vidro e aro bauhaus.
• Quadro 3 (Brutalismo Monolítico): Fundo brutalista, logo da marca e subtítulo '[SUBTITULO]' no terço superior, smartphone Preto Grafite deitado horizontalmente mostrando as lentes de câmera circulares e os 3 anéis protetores redondos escuros foscos.
• Quadro 4 (Maximalismo Vibrante): Fundo maximalista, logo da marca e subtítulo '[SUBTITULO]' no terço superior, close-up super macro em ângulo 3D com o anel protetor de lente circular e redondo metálico flutuando em corte de encaixe perfeito sobre a lente circular do celular.
--ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no camera lens, no DSLR lens, no photography camera, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                pl2Text: \`Adaptação multi-estilo Lote 2 em grade 2x2 para Frame de Lente: Mantenha a proporção 47:75. CADA UM DOS 4 QUADROS DEVE OBRIGATORIAMENTE EXIBIR O LOGO DA MARCA E O SUBTÍTULO '[SUBTITULO]' CENTRALIZADOS NO TERÇO SUPERIOR. TODOS OS PROTETORES DE LENTES DEVEM SER ESTRITAMENTE CIRCULARES E REDONDOS (ANÉIS METÁLICOS CIRCULARES E LENTES DE VIDRO CIRCULARES REDONDAS). Gere uma grade 2x2 com 4 quadros paralelos onde CADA QUADRO APLICA UM ESTILO ARTÍSTICO E UMA POSIÇÃO EXCLUSIVA DE PROTETORES DE LENTES CIRCULARES:
• Quadro 1 (Cyberpunk Neon): Fundo neon, logo da marca e subtítulo '[SUBTITULO]' no terço superior, vista da parte traseira inteira do smartphone Preto com o módulo de câmeras destacando os 3 anéis protetores de lentes circulares e redondos com aro neon.
• Quadro 2 (Luxo Dourado Mármore): Fundo mármore, logo da marca e subtítulo '[SUBTITULO]' no terço superior, somente os 3 anéis protetores de lentes de câmera circulares em ouro 3D redondos flutuando isolados com brilho de vidro e aro de ouro.
• Quadro 3 (Geométrico Abstrato 3D): Fundo cristalino, logo da marca e subtítulo '[SUBTITULO]' no terço superior, smartphone Prata deitado horizontalmente mostrando as lentes de câmera circulares e os anéis protetores redondos em cristal lapidado.
• Quadro 4 (Pop-Art Memphis): Fundo pop-art, logo da marca e subtítulo '[SUBTITULO]' no terço superior, close-up super macro em ângulo 3D com o anel protetor de lente circular e redondo colorido flutuando em corte de encaixe perfeito sobre a lente circular do celular.
--ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no camera lens, no DSLR lens, no photography camera, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                p2cText: \`Variação de cores 2x2: Gere 4 novas opções em grade 2x2 explorando paletas de cores distintas, vibrantes e contrastantes entre si em cada quadro, preservando obrigatoriamente em cada um dos 4 quadros o logo da marca, o subtítulo '[SUBTITULO]' no terço superior e o estilo visual da imagem anexada. Todos os anéis protetores de lentes devem ser estritamente circulares e redondos. Sem textos nas bordas ou molduras perimetrais. --ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                pl3Text: \`Adaptação multi-estilo Lote 3 em grade 2x2 para Frame de Lente: Mantenha a proporção 47:75. CADA UM DOS 4 QUADROS DEVE OBRIGATORIAMENTE EXIBIR O LOGO DA MARCA E O SUBTÍTULO '[SUBTITULO]' CENTRALIZADOS NO TERÇO SUPERIOR. TODOS OS PROTETORES DE LENTES DEVEM SER ESTRITAMENTE CIRCULARES E REDONDOS (ANÉIS METÁLICOS CIRCULARES E LENTES DE VIDRO CIRCULARES REDONDAS). Gere uma grade 2x2 com 4 quadros paralelos onde CADA QUADRO APLICA UM ESTILO ARTÍSTICO E UMA POSIÇÃO EXCLUSIVA DE PROTETORES DE LENTES CIRCULARES:
• Quadro 1 (Stealth Carbon Tech): Fundo de fibra de carbono, logo da marca e subtítulo '[SUBTITULO]' no terço superior, vista da parte traseira inteira do smartphone Preto Fosco com o módulo de câmeras destacando os 3 anéis protetores de lentes circulares e redondos em liga de carbono.
• Quadro 2 (Vaporwave Retro-Futurismo): Fundo gradiente 80s, logo da marca e subtítulo '[SUBTITULO]' no terço superior, somente os 3 anéis protetores de lentes de câmera circulares iridescentes redondos flutuando isolados com brilho de vidro e aro 80s.
• Quadro 3 (Sapphire Crystal): Fundo cristal azul, logo da marca e subtítulo '[SUBTITULO]' no terço superior, smartphone Azul Safira deitado horizontalmente mostrando as lentes de câmera circulares e os anéis protetores redondos em cristal lapidado.
• Quadro 4 (Titanium Industrial): Fundo titânio escovado, logo da marca e subtítulo '[SUBTITULO]' no terço superior, close-up super macro em ângulo 3D com o anel protetor de lente circular e redondo em metal técnico flutuando em corte de encaixe perfeito sobre a lente circular do celular.
--ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no camera lens, no DSLR lens, no photography camera, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                pl4Text: \`Adaptação multi-estilo Lote 4 em grade 2x2 para Frame de Lente: Mantenha a proporção 47:75. CADA UM DOS 4 QUADROS DEVE OBRIGATORIAMENTE EXIBIR O LOGO DA MARCA E O SUBTÍTULO '[SUBTITULO]' CENTRALIZADOS NO TERÇO SUPERIOR. TODOS OS PROTETORES DE LENTES DEVEM SER ESTRITAMENTE CIRCULARES E REDONDOS (ANÉIS METÁLICOS CIRCULARES E LENTES DE VIDRO CIRCULARES REDONDAS). Gere uma grade 2x2 com 4 quadros paralelos onde CADA QUADRO APLICA UM ESTILO ARTÍSTICO E UMA POSIÇÃO EXCLUSIVA DE PROTETORES DE LENTES CIRCULARES:
• Quadro 1 (Bento Grid Tech): Layout bento box estilo Apple, logo da marca e subtítulo '[SUBTITULO]' no terço superior, vista da parte traseira inteira do smartphone Prata com o módulo de câmeras destacando os 3 anéis protetores de lentes circulares e redondos metálicos clean.
• Quadro 2 (Liquid Chromium Acid Tech): Fundo mercúrio cromado, logo da marca e subtítulo '[SUBTITULO]' no terço superior, somente os 3 anéis protetores de lentes de câmera circulares cromados líquidos redondos flutuando isolados com brilho de vidro e aro espelhado.
• Quadro 3 (Glassmorphism Frosted): Fundo vidro fosco, logo da marca e subtítulo '[SUBTITULO]' no terço superior, smartphone Branco Estelar deitado horizontalmente mostrando as lentes de câmera circulares e os anéis protetores redondos jateados foscos.
• Quadro 4 (Y2K Glitch Matrix): Fundo matriz cibernética, logo da marca e subtítulo '[SUBTITULO]' no terço superior, close-up super macro em ângulo 3D com o anel protetor de lente circular e redondo estilo código neon flutuando em corte de encaixe perfeito sobre a lente circular do celular.
--ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no camera lens, no DSLR lens, no photography camera, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                p3cText: \`Variação de cores 2x2: Gere 4 novas opções em grade 2x2 explorando paletas de cores distintas, vibrantes e contrastantes entre si em cada quadro, preservando obrigatoriamente em cada um dos 4 quadros o logo da marca, o subtítulo '[SUBTITULO]' no terço superior e o estilo visual da imagem anexada. Todos os anéis protetores de lentes devem ser estritamente circulares e redondos. Sem textos nas bordas ou molduras perimetrais. --ar 47:75 --no square lens, no rectangular lens, no squarish camera bump, no square protectors, no icons, no badges, no box, no cutouts, no drawn holes, no 3d mockup, no text on borders, no thin borders\`,

                p4Text: \`Padronização rígida de proporção: Pegue exclusivamente a cartela escolhida da imagem anexada e renderize-a isolada como uma arte 2D plana contínua preenchendo 100% da tela na proporção física exata '47:75'. Re-enquadre e preserve integralmente TODOS os elementos gráficos da imagem anexada: mantenha perfeitamente o logo da marca, subtítulo '[SUBTITULO]' no terço superior e o estilo visual de fundo. Preencha 100% do enquadramento sem adicionar molduras perimetrais nem textos minúsculos perto das bordas. --ar 47:75 --no die-cut lines, no knife lines, no cutouts, no red contour lines, no holes, no 3d mockup, no text on borders, no thin borders\`,

                p6Text: \`Máscara de camada gráfica 2D direta universal: Utilize a primeira imagem anexada (Faca Mestre 3 Furos) estritamente como uma camada de máscara transparente de corte. Projete 100% do design gráfico da segunda imagem anexada por dentro da silhueta deste molde sem adicionar, remover ou alterar NENHUM elemento. Os três furos circulares e o recorte do topo da primeira imagem funcionam como aberturas vazadas transparentes de faca. Os três furos circulares devem manter exatamente Ø 68 px, com espaçamento uniforme de aproximadamente 16 px entre bordas. O furo da direita deve estar geometricamente equidistante dos dois furos da esquerda, posicionado no ponto médio perpendicular entre eles. Não alterar diâmetro, posição relativa ou geometria dos furos. Não mude de posição nenhum elemento gráfico ou artístico (incluindo textos, logos e fundos), a faca pode perfurar e cortar diretamente por cima de qualquer elemento exatamente onde ele está. Imagem 2D plana contínua perfeitamente alinhada. --ar 47:75 --no box, no 3d mockup, no altered geometry, no floating circles\`
            }`;

const startIdx = html.indexOf('standard: {');
const endIdx = html.indexOf('ultimate: {');

if (startIdx !== -1 && endIdx !== -1) {
    const before = html.substring(0, startIdx);
    const after = html.substring(endIdx);
    html = before + updatedStandardObj + ',\n' + after;
    fs.writeFileSync(htmlPath, html, 'utf8');
    console.log('Successfully updated standard frame prompts in apresentacao_frame.html!');
} else {
    console.error('Could not find startIdx or endIdx for standard block!');
}
